// Interaction check: pause/resume/stop and undo of a lesson.
import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", args: ["--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:3100/", { waitUntil: "networkidle" });
const count = () => page.evaluate(() => document.querySelectorAll('g[data-part="over"]').length);
await page.fill('textarea[aria-label="Your question"]', "Explain binary search");
await page.click("button.ask-btn");
await page.waitForSelector(".caption", { timeout: 20000 });
await page.waitForTimeout(3000);
await page.click("text=Pause");
const a = await count();
await page.waitForTimeout(3000);
const b = await count();
console.log("paused: elements before/after 3s =", a, b, "(should be equal)");
await page.click("text=Resume");
await page.waitForTimeout(4000);
const c = await count();
console.log("resumed: elements =", c, "(should grow)");
await page.click("button.pill.danger");
await page.waitForTimeout(500);
const stopped = await page.$("button.pill.danger");
console.log("stopped:", !stopped, "elements kept:", await count());
await page.keyboard.press("Control+z");
await page.waitForTimeout(300);
console.log("after undo, elements:", await count(), "(should be 0)");
await page.keyboard.press("Control+Shift+z");
await page.waitForTimeout(300);
console.log("after redo, elements:", await count());
console.log("page errors:", errors);
await browser.close();
